[project]
name = "experiments-hinagata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.0",
    "pyyaml>=6.0.2",
    "tensorboard>=2.20.0",
    "torch>=2.7.1",
]
